import 'package:dexpro/core/models/ability.dart';
import 'package:dexpro/core/models/move.dart';
import 'package:dexpro/core/models/type.dart';
import 'package:dexpro/core/models/stats.dart';

class Pokemon {
  const Pokemon({
    required this.id,
    required this.type1,
    this.type2,
    required this.stats,
    required this.ability,
    this.ability2,
    this.hiddenAbility,
    this.form,
    this.moves = const <Move>[],
    this.mega,
    this.mega2,
  });

  final int id;
  final Type type1;
  final Type? type2;
  final Stats stats;
  final Ability ability;
  final Ability? ability2;
  final Ability? hiddenAbility;
  final String? form;
  final List<Move> moves;
  final Pokemon? mega;
  final Pokemon? mega2;

  String padL(int x) => x.toString().padLeft(4, '0');

  String get imageURL =>
      'assets/pokemon/120px-Menu_CP_${padL(id)}${form == null ? '' : '-$form'}.png';

  String get shinyImageURL =>
      'assets/pokemon/120px-Menu_CP_${padL(id)}${form == null ? '' : '-$form'}_shiny.png';
}

final Map<String, Pokemon> pokemonList = {
  'venusaur': Pokemon(
    id: 3,
    type1: Type.grass,
    type2: Type.poison,
    stats: Stats(hp: 80, att: 82, def: 83, spa: 100, spd: 100, spe: 80),
    ability: Ability.overgrow,
    hiddenAbility: Ability.chlorophyll,
    moves: venusaurMoves,
    mega: Pokemon(
      id: 3,
      type1: Type.grass,
      type2: Type.poison,
      stats: Stats(hp: 80, att: 100, def: 123, spa: 122, spd: 120, spe: 80),
      ability: Ability.thickFat,
      form: 'Mega',
      moves: venusaurMoves,
    ),
  ),
  'charizard': Pokemon(
    id: 6,
    type1: Type.fire,
    type2: Type.flying,
    stats: Stats(hp: 78, att: 84, def: 78, spa: 109, spd: 85, spe: 100),
    ability: Ability.blaze,
    hiddenAbility: Ability.solarPower,
    moves: charizardMoves,
    mega: Pokemon(
      id: 6,
      type1: Type.fire,
      type2: Type.dragon,
      stats: Stats(hp: 78, att: 130, def: 111, spa: 130, spd: 85, spe: 100),
      ability: Ability.toughClaws,
      form: 'Mega_X',
      moves: charizardMoves,
    ),
    mega2: Pokemon(
      id: 6,
      type1: Type.fire,
      type2: Type.flying,
      stats: Stats(hp: 78, att: 104, def: 78, spa: 159, spd: 115, spe: 100),
      ability: Ability.drought,
      form: 'Mega_Y',
      moves: charizardMoves,
    ),
  ),
  'blastoise': Pokemon(
    id: 9,
    type1: Type.water,
    stats: Stats(hp: 79, att: 83, def: 100, spa: 85, spd: 105, spe: 78),
    ability: Ability.torrent,
    hiddenAbility: Ability.rainDish,
    moves: blastoiseMoves,
    mega: Pokemon(
      id: 9,
      type1: Type.water,
      stats: Stats(hp: 79, att: 103, def: 120, spa: 135, spd: 115, spe: 78),
      ability: Ability.megaLauncher,
      moves: blastoiseMoves,
      form: 'Mega',
    ),
  ),
  'beedrill': Pokemon(
    id: 15,
    type1: Type.bug,
    type2: Type.poison,
    stats: Stats(hp: 65, att: 90, def: 40, spa: 45, spd: 80, spe: 75),
    ability: Ability.swarm,
    hiddenAbility: Ability.sniper,
    moves: beedrillMoves,
    mega: Pokemon(
      id: 15,
      type1: Type.bug,
      type2: Type.poison,
      stats: Stats(hp: 65, att: 150, def: 40, spa: 15, spd: 80, spe: 145),
      ability: Ability.adaptability,
      moves: beedrillMoves,
      form: 'Mega',
    ),
  ),
  'pidgeot': Pokemon(
    id: 18,
    type1: Type.normal,
    type2: Type.flying,
    stats: Stats(hp: 83, att: 80, def: 75, spa: 70, spd: 70, spe: 101),
    ability: Ability.keenEye,
    hiddenAbility: Ability.bigPecks,
    moves: pidgeotMoves,
    mega: Pokemon(
      id: 18,
      type1: Type.normal,
      type2: Type.flying,
      stats: Stats(hp: 83, att: 80, def: 80, spa: 135, spd: 80, spe: 121),
      ability: Ability.noGuard,
      moves: pidgeotMoves,
      form: 'Mega',
    ),
  ),
  'arbok': Pokemon(
    id: 24,
    type1: Type.poison,
    type2: null,
    stats: Stats(hp: 60, att: 95, def: 69, spa: 65, spd: 79, spe: 80),
    ability: Ability.intimidate,
    ability2: Ability.shedSkin,
    hiddenAbility: Ability.unnerve,
    moves: arbokMoves,
  ),

  'pikachu': Pokemon(
    id: 25,
    type1: Type.electric,
    type2: null,
    stats: Stats(hp: 35, att: 55, def: 40, spa: 50, spd: 50, spe: 90),
    ability: Ability.static,
    ability2: null,
    hiddenAbility: Ability.lightningRod,
    moves: pikachuMoves,
  ),

  'raichu': Pokemon(
    id: 26,
    type1: Type.electric,
    type2: null,
    stats: Stats(hp: 60, att: 90, def: 55, spa: 90, spd: 80, spe: 110),
    ability: Ability.static,
    ability2: null,
    hiddenAbility: Ability.lightningRod,
    moves: raichuMoves,
  ),

  'raichu (Alola)': Pokemon(
    id: 26,
    type1: Type.electric,
    type2: Type.psychic,
    stats: Stats(hp: 60, att: 85, def: 50, spa: 95, spd: 85, spe: 110),
    ability: Ability.surgeSurfer,
    ability2: null,
    hiddenAbility: null,
    moves: raichuAlolaMoves,
    form: 'Alola',
  ),

  'clefable': Pokemon(
    id: 36,
    type1: Type.fairy,
    type2: null,
    stats: Stats(hp: 95, att: 70, def: 73, spa: 95, spd: 90, spe: 60),
    ability: Ability.cuteCharm,
    ability2: Ability.magicGuard,
    hiddenAbility: Ability.unaware,
    moves: clefableMoves,
    mega: Pokemon(
      id: 36,
      type1: Type.fairy,
      stats: Stats(hp: 95, att: 80, def: 93, spa: 135, spd: 110, spe: 70),
      ability: Ability.magicBounce,
      moves: clefableMoves,
      form: 'Mega',
    ),
  ),

  'ninetales': Pokemon(
    id: 38,
    type1: Type.fire,
    type2: null,
    stats: Stats(hp: 73, att: 76, def: 75, spa: 81, spd: 100, spe: 100),
    ability: Ability.flashFire,
    ability2: null,
    hiddenAbility: Ability.drought,
    moves: ninetalesMoves,
  ),

  'ninetales (Alola)': Pokemon(
    id: 38,
    type1: Type.ice,
    type2: Type.fairy,
    stats: Stats(hp: 73, att: 67, def: 75, spa: 81, spd: 100, spe: 109),
    ability: Ability.snowCloak,
    ability2: null,
    hiddenAbility: Ability.snowWarning,
    moves: ninetalesAlolaMoves,
    form: 'Alola',
  ),

  'arcanine': Pokemon(
    id: 59,
    type1: Type.fire,
    type2: null,
    stats: Stats(hp: 90, att: 110, def: 80, spa: 100, spd: 80, spe: 95),
    ability: Ability.intimidate,
    ability2: Ability.flashFire,
    hiddenAbility: Ability.justified,
    moves: arcanineMoves,
  ),

  'arcanine (Hisui)': Pokemon(
    id: 59,
    type1: Type.fire,
    type2: Type.rock,
    stats: Stats(hp: 95, att: 115, def: 80, spa: 95, spd: 80, spe: 90),
    ability: Ability.intimidate,
    ability2: Ability.flashFire,
    hiddenAbility: Ability.rockHead,
    moves: arcanineHisuiMoves,
    form: 'Hisui',
  ),

  'alakazam': Pokemon(
    id: 65,
    type1: Type.psychic,
    type2: null,
    stats: Stats(hp: 55, att: 50, def: 45, spa: 135, spd: 95, spe: 120),
    ability: Ability.synchronize,
    ability2: Ability.innerFocus,
    hiddenAbility: Ability.magicGuard,
    moves: alakazamMoves,
    mega: Pokemon(
      id: 65,
      type1: Type.psychic,
      type2: null,
      stats: Stats(hp: 55, att: 50, def: 65, spa: 175, spd: 105, spe: 150),
      ability: Ability.trace,
      ability2: null,
      hiddenAbility: null,
      moves: alakazamMoves,
      form: 'Mega',
    ),
  ),

  'machamp': Pokemon(
    id: 68,
    type1: Type.fighting,
    type2: null,
    stats: Stats(hp: 90, att: 130, def: 80, spa: 65, spd: 85, spe: 55),
    ability: Ability.guts,
    ability2: Ability.noGuard,
    hiddenAbility: Ability.steadfast,
    moves: machampMoves,
  ),

  'victreebel': Pokemon(
    id: 71,
    type1: Type.grass,
    type2: Type.poison,
    stats: Stats(hp: 80, att: 105, def: 65, spa: 100, spd: 70, spe: 70),
    ability: Ability.chlorophyll,
    ability2: null,
    hiddenAbility: Ability.gluttony,
    moves: victreebelMoves,
    mega: Pokemon(
      id: 71,
      type1: Type.grass,
      type2: Type.poison,
      stats: Stats(hp: 80, att: 125, def: 85, spa: 135, spd: 95, spe: 70),
      ability: Ability.innardsOut,
      moves: victreebelMoves,
      form: 'Mega',
    ),
  ),

  'slowbro': Pokemon(
    id: 80,
    type1: Type.water,
    type2: Type.psychic,
    stats: Stats(hp: 95, att: 75, def: 110, spa: 100, spd: 80, spe: 30),
    ability: Ability.oblivious,
    ability2: Ability.ownTempo,
    hiddenAbility: Ability.regenerator,
    moves: slowbroMoves,
    mega: Pokemon(
      id: 80,
      type1: Type.water,
      type2: Type.psychic,
      stats: Stats(hp: 95, att: 75, def: 180, spa: 130, spd: 80, spe: 30),
      ability: Ability.shellArmor,
      moves: slowbroMoves,
      form: 'Mega',
    ),
  ),

  'slowbro (Galar)': Pokemon(
    id: 80,
    type1: Type.poison,
    type2: Type.psychic,
    stats: Stats(hp: 95, att: 100, def: 95, spa: 100, spd: 70, spe: 30),
    ability: Ability.quickDraw,
    ability2: Ability.ownTempo,
    hiddenAbility: Ability.regenerator,
    moves: slowbroGalarMoves,
    form: 'Galar',
  ),

  'gengar': Pokemon(
    id: 94,
    type1: Type.ghost,
    type2: Type.poison,
    stats: Stats(hp: 60, att: 65, def: 60, spa: 130, spd: 75, spe: 110),
    ability: Ability.cursedBody,
    ability2: null,
    hiddenAbility: null,
    moves: gengarMoves,
    mega: Pokemon(
      id: 94,
      type1: Type.ghost,
      type2: Type.poison,
      stats: Stats(hp: 60, att: 65, def: 80, spa: 170, spd: 95, spe: 130),
      ability: Ability.shadowTag,
      ability2: null,
      hiddenAbility: null,
      moves: gengarMoves,
      form: 'Mega',
    ),
  ),

  'kangaskhan': Pokemon(
    id: 115,
    type1: Type.normal,
    type2: null,
    stats: Stats(hp: 105, att: 95, def: 80, spa: 40, spd: 80, spe: 90),
    ability: Ability.earlyBird,
    ability2: Ability.scrappy,
    hiddenAbility: Ability.innerFocus,
    moves: kangaskhanMoves,
    mega: Pokemon(
      id: 115,
      type1: Type.normal,
      type2: null,
      stats: Stats(hp: 105, att: 125, def: 100, spa: 60, spd: 100, spe: 100),
      ability: Ability.parentalBond,
      ability2: null,
      hiddenAbility: null,
      moves: kangaskhanMoves,
      form: 'Mega',
    ),
  ),

  'starmie': Pokemon(
    id: 121,
    type1: Type.water,
    type2: Type.psychic,
    stats: Stats(hp: 60, att: 75, def: 85, spa: 100, spd: 85, spe: 115),
    ability: Ability.illuminate,
    ability2: Ability.naturalCure,
    hiddenAbility: Ability.analytic,
    moves: starmieMoves,
    mega: Pokemon(
      id: 121,
      type1: Type.water,
      type2: Type.psychic,
      stats: Stats(hp: 60, att: 100, def: 105, spa: 130, spd: 105, spe: 120),
      ability: Ability.hugePower,
      moves: starmieMoves,
      form: 'Mega',
    ),
  ),

  'pinsir': Pokemon(
    id: 127,
    type1: Type.bug,
    type2: null,
    stats: Stats(hp: 65, att: 125, def: 100, spa: 55, spd: 70, spe: 85),
    ability: Ability.hyperCutter,
    ability2: Ability.moldBreaker,
    hiddenAbility: Ability.moxie,
    moves: pinsirMoves,
    mega: Pokemon(
      id: 127,
      type1: Type.bug,
      type2: Type.flying,
      stats: Stats(hp: 65, att: 155, def: 120, spa: 65, spd: 90, spe: 105),
      ability: Ability.aerilate,
      ability2: null,
      hiddenAbility: null,
      moves: pinsirMoves,
      form: 'Mega',
    ),
  ),

  'tauros': Pokemon(
    id: 128,
    type1: Type.normal,
    type2: null,
    stats: Stats(hp: 75, att: 100, def: 95, spa: 40, spd: 70, spe: 110),
    ability: Ability.intimidate,
    ability2: Ability.angerPoint,
    hiddenAbility: Ability.sheerForce,
    moves: taurosMoves,
  ),

  'tauros (Paldea-Combat)': Pokemon(
    id: 128,
    type1: Type.fighting,
    type2: null,
    stats: Stats(hp: 75, att: 110, def: 105, spa: 30, spd: 70, spe: 100),
    ability: Ability.intimidate,
    ability2: Ability.angerPoint,
    hiddenAbility: Ability.cudChew,
    moves: taurosPaldeaCombatBreedMoves,
    form: 'Paldea_Combat',
  ),

  'tauros (Paldea-Blaze)': Pokemon(
    id: 128,
    type1: Type.fighting,
    type2: Type.fire,
    stats: Stats(hp: 75, att: 110, def: 105, spa: 30, spd: 70, spe: 100),
    ability: Ability.intimidate,
    ability2: Ability.angerPoint,
    hiddenAbility: Ability.cudChew,
    moves: taurosPaldeaBlazeBreedMoves,
    form: 'Paldea_Blaze',
  ),

  'tauros (Paldea-Aqua)': Pokemon(
    id: 128,
    type1: Type.fighting,
    type2: Type.water,
    stats: Stats(hp: 75, att: 110, def: 105, spa: 30, spd: 70, spe: 100),
    ability: Ability.intimidate,
    ability2: Ability.angerPoint,
    hiddenAbility: Ability.cudChew,
    moves: taurosPaldeaAquaBreedMoves,
    form: 'Paldea_Aqua',
  ),

  'gyarados': Pokemon(
    id: 130,
    type1: Type.water,
    type2: Type.flying,
    stats: Stats(hp: 95, att: 125, def: 79, spa: 60, spd: 100, spe: 81),
    ability: Ability.intimidate,
    ability2: null,
    hiddenAbility: Ability.moxie,
    moves: gyaradosMoves,
    mega: Pokemon(
      id: 130,
      type1: Type.water,
      type2: Type.dark,
      stats: Stats(hp: 95, att: 155, def: 109, spa: 70, spd: 130, spe: 81),
      ability: Ability.moldBreaker,
      ability2: null,
      hiddenAbility: null,
      moves: gyaradosMoves,
      form: 'Mega',
    ),
  ),

  'ditto': Pokemon(
    id: 132,
    type1: Type.normal,
    type2: null,
    stats: Stats(hp: 48, att: 48, def: 48, spa: 48, spd: 48, spe: 48),
    ability: Ability.limber,
    ability2: null,
    hiddenAbility: Ability.imposter,
    moves: dittoMoves,
  ),

  'vaporeon': Pokemon(
    id: 134,
    type1: Type.water,
    type2: null,
    stats: Stats(hp: 130, att: 65, def: 60, spa: 110, spd: 95, spe: 65),
    ability: Ability.waterAbsorb,
    ability2: null,
    hiddenAbility: Ability.hydration,
    moves: vaporeonMoves,
  ),

  'jolteon': Pokemon(
    id: 135,
    type1: Type.electric,
    type2: null,
    stats: Stats(hp: 65, att: 65, def: 60, spa: 110, spd: 95, spe: 130),
    ability: Ability.voltAbsorb,
    ability2: null,
    hiddenAbility: Ability.quickFeet,
    moves: jolteonMoves,
  ),

  'flareon': Pokemon(
    id: 136,
    type1: Type.fire,
    type2: null,
    stats: Stats(hp: 65, att: 130, def: 60, spa: 95, spd: 110, spe: 65),
    ability: Ability.flashFire,
    ability2: null,
    hiddenAbility: Ability.guts,
    moves: flareonMoves,
  ),
  'aerodactyl': Pokemon(
    id: 142,
    type1: Type.rock,
    type2: Type.flying,
    stats: Stats(hp: 80, att: 105, def: 65, spa: 60, spd: 75, spe: 130),
    ability: Ability.rockHead,
    ability2: Ability.pressure,
    hiddenAbility: Ability.unnerve,
    moves: aerodactylMoves,
    mega: Pokemon(
      id: 142,
      type1: Type.rock,
      type2: Type.flying,
      stats: Stats(hp: 80, att: 135, def: 85, spa: 70, spd: 95, spe: 150),
      ability: Ability.toughClaws,
      ability2: null,
      hiddenAbility: null,
      moves: aerodactylMoves,
      form: 'Mega',
    ),
  ),

  'snorlax': Pokemon(
    id: 143,
    type1: Type.normal,
    type2: null,
    stats: Stats(hp: 160, att: 110, def: 65, spa: 65, spd: 110, spe: 30),
    ability: Ability.immunity,
    ability2: Ability.thickFat,
    hiddenAbility: Ability.gluttony,
    moves: snorlaxMoves,
  ),

  'dragonite': Pokemon(
    id: 149,
    type1: Type.dragon,
    type2: Type.flying,
    stats: Stats(hp: 91, att: 134, def: 95, spa: 100, spd: 100, spe: 80),
    ability: Ability.innerFocus,
    ability2: null,
    hiddenAbility: Ability.multiscale,
    moves: dragoniteMoves,
    mega: Pokemon(
      id: 149,
      type1: Type.dragon,
      type2: Type.flying,
      stats: Stats(hp: 91, att: 124, def: 115, spa: 145, spd: 125, spe: 100),
      ability: Ability.multiscale,
      moves: dragoniteMoves,
      form: 'Mega',
    ),
  ),

  'meganium': Pokemon(
    id: 154,
    type1: Type.grass,
    type2: null,
    stats: Stats(hp: 80, att: 82, def: 100, spa: 83, spd: 100, spe: 80),
    ability: Ability.overgrow,
    ability2: null,
    hiddenAbility: Ability.leafGuard,
    moves: meganiumMoves,
    mega: Pokemon(
      id: 154,
      type1: Type.grass,
      type2: Type.fairy,
      stats: Stats(hp: 80, att: 92, def: 115, spa: 143, spd: 115, spe: 80),
      ability: Ability.megaSol,
      moves: meganiumMoves,
      form: 'Mega',
    ),
  ),

  'typhlosion': Pokemon(
    id: 157,
    type1: Type.fire,
    type2: null,
    stats: Stats(hp: 78, att: 84, def: 78, spa: 109, spd: 85, spe: 100),
    ability: Ability.blaze,
    ability2: null,
    hiddenAbility: Ability.flashFire,
    moves: typhlosionMoves,
  ),

  'typhlosion (Hisui)': Pokemon(
    id: 157,
    type1: Type.fire,
    type2: Type.ghost,
    stats: Stats(hp: 73, att: 84, def: 78, spa: 119, spd: 85, spe: 95),
    ability: Ability.blaze,
    ability2: null,
    hiddenAbility: Ability.frisk,
    moves: typhlosionHisuiMoves,
    form: 'Hisui',
  ),

  'feraligatr': Pokemon(
    id: 160,
    type1: Type.water,
    type2: null,
    stats: Stats(hp: 85, att: 105, def: 100, spa: 79, spd: 83, spe: 78),
    ability: Ability.torrent,
    ability2: null,
    hiddenAbility: Ability.sheerForce,
    moves: feraligatrMoves,
    mega: Pokemon(
      id: 160,
      type1: Type.water,
      type2: Type.dragon,
      stats: Stats(hp: 85, att: 160, def: 125, spa: 89, spd: 93, spe: 78),
      ability: Ability.dragonize,
      moves: feraligatrMoves,
      form: 'Mega',
    ),
  ),

  'ariados': Pokemon(
    id: 168,
    type1: Type.bug,
    type2: Type.poison,
    stats: Stats(hp: 70, att: 90, def: 70, spa: 60, spd: 70, spe: 40),
    ability: Ability.swarm,
    ability2: Ability.insomnia,
    hiddenAbility: Ability.sniper,
    moves: ariadosMoves,
  ),

  'ampharos': Pokemon(
    id: 181,
    type1: Type.electric,
    type2: null,
    stats: Stats(hp: 90, att: 75, def: 85, spa: 115, spd: 90, spe: 55),
    ability: Ability.static,
    ability2: null,
    hiddenAbility: Ability.plus,
    moves: ampharosMoves,
    mega: Pokemon(
      id: 181,
      type1: Type.electric,
      type2: Type.dragon,
      stats: Stats(hp: 90, att: 95, def: 105, spa: 165, spd: 110, spe: 45),
      ability: Ability.moldBreaker,
      ability2: null,
      hiddenAbility: null,
      moves: ampharosMoves,
      form: 'Mega',
    ),
  ),

  'azumarill': Pokemon(
    id: 184,
    type1: Type.water,
    type2: Type.fairy,
    stats: Stats(hp: 100, att: 50, def: 80, spa: 60, spd: 80, spe: 50),
    ability: Ability.thickFat,
    ability2: Ability.hugePower,
    hiddenAbility: Ability.sapSipper,
    moves: azumarillMoves,
  ),

  'politoed': Pokemon(
    id: 186,
    type1: Type.water,
    type2: null,
    stats: Stats(hp: 90, att: 75, def: 75, spa: 90, spd: 100, spe: 70),
    ability: Ability.waterAbsorb,
    ability2: Ability.damp,
    hiddenAbility: Ability.drizzle,
    moves: politoedMoves,
  ),

  'espeon': Pokemon(
    id: 196,
    type1: Type.psychic,
    type2: null,
    stats: Stats(hp: 65, att: 65, def: 60, spa: 130, spd: 95, spe: 110),
    ability: Ability.synchronize,
    ability2: null,
    hiddenAbility: Ability.magicBounce,
    moves: espeonMoves,
  ),

  'umbreon': Pokemon(
    id: 197,
    type1: Type.dark,
    type2: null,
    stats: Stats(hp: 95, att: 65, def: 110, spa: 60, spd: 130, spe: 65),
    ability: Ability.synchronize,
    ability2: null,
    hiddenAbility: Ability.innerFocus,
    moves: umbreonMoves,
  ),

  'slowking': Pokemon(
    id: 199,
    type1: Type.water,
    type2: Type.psychic,
    stats: Stats(hp: 95, att: 75, def: 80, spa: 100, spd: 110, spe: 30),
    ability: Ability.oblivious,
    ability2: Ability.ownTempo,
    hiddenAbility: Ability.regenerator,
    moves: slowkingMoves,
  ),

  'slowking (Galar)': Pokemon(
    id: 199,
    type1: Type.poison,
    type2: Type.psychic,
    stats: Stats(hp: 95, att: 65, def: 80, spa: 110, spd: 110, spe: 30),
    ability: Ability.curiousMedicine,
    ability2: null,
    hiddenAbility: Ability.regenerator,
    moves: slowkingGalarMoves,
    form: 'Galar',
  ),

  'forretress': Pokemon(
    id: 205,
    type1: Type.bug,
    type2: Type.steel,
    stats: Stats(hp: 75, att: 90, def: 140, spa: 60, spd: 60, spe: 40),
    ability: Ability.sturdy,
    ability2: null,
    hiddenAbility: Ability.overcoat,
    moves: forretressMoves,
  ),

  'steelix': Pokemon(
    id: 208,
    type1: Type.steel,
    type2: Type.ground,
    stats: Stats(hp: 75, att: 85, def: 200, spa: 55, spd: 65, spe: 30),
    ability: Ability.rockHead,
    ability2: Ability.sturdy,
    hiddenAbility: Ability.sheerForce,
    moves: steelixMoves,
    mega: Pokemon(
      id: 208,
      type1: Type.steel,
      type2: Type.ground,
      stats: Stats(hp: 75, att: 125, def: 230, spa: 55, spd: 95, spe: 30),
      ability: Ability.sandForce,
      moves: steelixMoves,
      form: 'Mega',
    ),
  ),

  'scizor': Pokemon(
    id: 212,
    type1: Type.bug,
    type2: Type.steel,
    stats: Stats(hp: 70, att: 130, def: 100, spa: 55, spd: 80, spe: 65),
    ability: Ability.swarm,
    ability2: Ability.technician,
    hiddenAbility: Ability.lightMetal,
    moves: scizorMoves,
    mega: Pokemon(
      id: 212,
      type1: Type.bug,
      type2: Type.steel,
      stats: Stats(hp: 70, att: 150, def: 140, spa: 65, spd: 100, spe: 75),
      ability: Ability.technician,
      ability2: null,
      hiddenAbility: null,
      moves: scizorMoves,
      form: 'Mega',
    ),
  ),

  'heracross': Pokemon(
    id: 214,
    type1: Type.bug,
    type2: Type.fighting,
    stats: Stats(hp: 80, att: 125, def: 75, spa: 40, spd: 95, spe: 85),
    ability: Ability.swarm,
    ability2: Ability.guts,
    hiddenAbility: Ability.moxie,
    moves: heracrossMoves,
    mega: Pokemon(
      id: 214,
      type1: Type.bug,
      type2: Type.fighting,
      stats: Stats(hp: 80, att: 185, def: 115, spa: 40, spd: 105, spe: 75),
      ability: Ability.skillLink,
      ability2: null,
      hiddenAbility: null,
      moves: heracrossMoves,
      form: 'Mega',
    ),
  ),

  'skarmory': Pokemon(
    id: 227,
    type1: Type.steel,
    type2: Type.flying,
    stats: Stats(hp: 65, att: 80, def: 140, spa: 40, spd: 70, spe: 70),
    ability: Ability.keenEye,
    ability2: Ability.sturdy,
    hiddenAbility: Ability.weakArmor,
    moves: skarmoryMoves,
    mega: Pokemon(
      id: 227,
      type1: Type.steel,
      type2: Type.flying,
      stats: Stats(hp: 65, att: 140, def: 110, spa: 40, spd: 100, spe: 110),
      ability: Ability.stalwart,
      moves: skarmoryMoves,
      form: 'Mega',
    ),
  ),

  'houndoom': Pokemon(
    id: 229,
    type1: Type.dark,
    type2: Type.fire,
    stats: Stats(hp: 75, att: 90, def: 50, spa: 110, spd: 80, spe: 95),
    ability: Ability.earlyBird,
    ability2: Ability.flashFire,
    hiddenAbility: Ability.unnerve,
    moves: houndoomMoves,
    mega: Pokemon(
      id: 229,
      type1: Type.dark,
      type2: Type.fire,
      stats: Stats(hp: 75, att: 90, def: 90, spa: 140, spd: 90, spe: 115),
      ability: Ability.solarPower,
      ability2: null,
      hiddenAbility: null,
      moves: houndoomMoves,
      form: 'Mega',
    ),
  ),

  'tyranitar': Pokemon(
    id: 248,
    type1: Type.rock,
    type2: Type.dark,
    stats: Stats(hp: 100, att: 134, def: 110, spa: 95, spd: 100, spe: 61),
    ability: Ability.sandStream,
    ability2: null,
    hiddenAbility: Ability.unnerve,
    moves: tyranitarMoves,
    mega: Pokemon(
      id: 248,
      type1: Type.rock,
      type2: Type.dark,
      stats: Stats(hp: 100, att: 164, def: 150, spa: 95, spd: 120, spe: 71),
      ability: Ability.sandStream,
      ability2: null,
      hiddenAbility: null,
      moves: tyranitarMoves,
      form: 'Mega',
    ),
  ),

  'pelipper': Pokemon(
    id: 279,
    type1: Type.water,
    type2: Type.flying,
    stats: Stats(hp: 60, att: 50, def: 100, spa: 95, spd: 70, spe: 65),
    ability: Ability.keenEye,
    ability2: Ability.drizzle,
    hiddenAbility: Ability.rainDish,
    moves: pelipperMoves,
  ),

  'gardevoir': Pokemon(
    id: 282,
    type1: Type.psychic,
    type2: Type.fairy,
    stats: Stats(hp: 68, att: 65, def: 65, spa: 125, spd: 115, spe: 80),
    ability: Ability.synchronize,
    ability2: Ability.trace,
    hiddenAbility: Ability.telepathy,
    moves: gardevoirMoves,
    mega: Pokemon(
      id: 282,
      type1: Type.psychic,
      type2: Type.fairy,
      stats: Stats(hp: 68, att: 85, def: 65, spa: 165, spd: 135, spe: 100),
      ability: Ability.pixilate,
      moves: gardevoirMoves,
      form: 'Mega',
    ),
  ),

  'sableye': Pokemon(
    id: 302,
    type1: Type.dark,
    type2: Type.ghost,
    stats: Stats(hp: 50, att: 75, def: 75, spa: 65, spd: 65, spe: 50),
    ability: Ability.keenEye,
    ability2: Ability.stall,
    hiddenAbility: Ability.prankster,
    moves: sableyeMoves,
    mega: Pokemon(
      id: 302,
      type1: Type.dark,
      type2: Type.ghost,
      stats: Stats(hp: 50, att: 85, def: 125, spa: 85, spd: 115, spe: 20),
      ability: Ability.magicBounce,
      moves: sableyeMoves,
      form: 'Mega',
    ),
  ),

  'aggron': Pokemon(
    id: 306,
    type1: Type.steel,
    type2: Type.rock,
    stats: Stats(hp: 70, att: 110, def: 180, spa: 60, spd: 60, spe: 50),
    ability: Ability.sturdy,
    ability2: Ability.rockHead,
    hiddenAbility: Ability.heavyMetal,
    moves: aggronMoves,
    mega: Pokemon(
      id: 306,
      type1: Type.steel,
      stats: Stats(hp: 70, att: 140, def: 230, spa: 60, spd: 80, spe: 50),
      ability: Ability.filter,
      moves: aggronMoves,
      form: 'Mega',
    ),
  ),

  'medicham': Pokemon(
    id: 308,
    type1: Type.fighting,
    type2: Type.psychic,
    stats: Stats(hp: 60, att: 60, def: 75, spa: 60, spd: 75, spe: 80),
    ability: Ability.purePower,
    ability2: null,
    hiddenAbility: Ability.telepathy,
    moves: medichamMoves,
    mega: Pokemon(
      id: 308,
      type1: Type.fighting,
      type2: Type.psychic,
      stats: Stats(hp: 60, att: 100, def: 85, spa: 80, spd: 85, spe: 100),
      ability: Ability.purePower,
      moves: medichamMoves,
      form: 'Mega',
    ),
  ),

  'manectric': Pokemon(
    id: 310,
    type1: Type.electric,
    type2: null,
    stats: Stats(hp: 70, att: 75, def: 60, spa: 105, spd: 60, spe: 105),
    ability: Ability.static,
    ability2: Ability.lightningRod,
    hiddenAbility: Ability.minus,
    moves: manectricMoves,
    mega: Pokemon(
      id: 310,
      type1: Type.electric,
      type2: null,
      stats: Stats(hp: 70, att: 75, def: 80, spa: 135, spd: 80, spe: 135),
      ability: Ability.intimidate,
      moves: manectricMoves,
      form: 'Mega',
    ),
  ),

  'sharpedo': Pokemon(
    id: 319,
    type1: Type.water,
    type2: Type.dark,
    stats: Stats(hp: 70, att: 120, def: 40, spa: 95, spd: 40, spe: 95),
    ability: Ability.roughSkin,
    ability2: null,
    hiddenAbility: Ability.speedBoost,
    moves: sharpedoMoves,
    mega: Pokemon(
      id: 319,
      type1: Type.water,
      type2: Type.dark,
      stats: Stats(hp: 70, att: 140, def: 70, spa: 110, spd: 65, spe: 105),
      ability: Ability.strongJaw,
      moves: sharpedoMoves,
      form: 'Mega',
    ),
  ),

  'camerupt': Pokemon(
    id: 323,
    type1: Type.fire,
    type2: Type.ground,
    stats: Stats(hp: 70, att: 100, def: 70, spa: 105, spd: 75, spe: 40),
    ability: Ability.magmaArmor,
    ability2: Ability.solidRock,
    hiddenAbility: Ability.angerPoint,
    moves: cameruptMoves,
    mega: Pokemon(
      id: 323,
      type1: Type.fire,
      type2: Type.ground,
      stats: Stats(hp: 70, att: 120, def: 100, spa: 145, spd: 105, spe: 20),
      ability: Ability.sheerForce,
      moves: cameruptMoves,
      form: 'Mega',
    ),
  ),

  'torkoal': Pokemon(
    id: 324,
    type1: Type.fire,
    type2: null,
    stats: Stats(hp: 70, att: 85, def: 140, spa: 85, spd: 70, spe: 20),
    ability: Ability.whiteSmoke,
    ability2: Ability.drought,
    hiddenAbility: Ability.shellArmor,
    moves: torkoalMoves,
  ),

  'altaria': Pokemon(
    id: 334,
    type1: Type.dragon,
    type2: Type.flying,
    stats: Stats(hp: 75, att: 70, def: 90, spa: 70, spd: 105, spe: 80),
    ability: Ability.naturalCure,
    ability2: null,
    hiddenAbility: Ability.cloudNine,
    moves: altariaMoves,
    mega: Pokemon(
      id: 334,
      type1: Type.dragon,
      type2: Type.fairy,
      stats: Stats(hp: 75, att: 110, def: 110, spa: 110, spd: 105, spe: 80),
      ability: Ability.pixilate,
      ability2: null,
      hiddenAbility: null,
      moves: altariaMoves,
      form: 'Mega',
    ),
  ),

  'milotic': Pokemon(
    id: 350,
    type1: Type.water,
    type2: null,
    stats: Stats(hp: 95, att: 60, def: 79, spa: 100, spd: 125, spe: 81),
    ability: Ability.marvelScale,
    ability2: Ability.competitive,
    hiddenAbility: Ability.cuteCharm,
    moves: miloticMoves,
  ),

  'castform': Pokemon(
    id: 351,
    type1: Type.normal,
    type2: null,
    stats: Stats(hp: 70, att: 70, def: 70, spa: 70, spd: 70, spe: 70),
    ability: Ability.forecast,
    ability2: null,
    hiddenAbility: null,
    moves: castformMoves,
  ),

  'banette': Pokemon(
    id: 354,
    type1: Type.ghost,
    type2: null,
    stats: Stats(hp: 64, att: 115, def: 65, spa: 83, spd: 63, spe: 65),
    ability: Ability.insomnia,
    ability2: Ability.frisk,
    hiddenAbility: Ability.cursedBody,
    moves: banetteMoves,
    mega: Pokemon(
      id: 354,
      type1: Type.ghost,
      type2: null,
      stats: Stats(hp: 64, att: 165, def: 75, spa: 93, spd: 83, spe: 75),
      ability: Ability.prankster,
      ability2: null,
      hiddenAbility: null,
      moves: banetteMoves,
      form: 'Mega',
    ),
  ),

  'chimecho': Pokemon(
    id: 358,
    type1: Type.psychic,
    type2: null,
    stats: Stats(hp: 75, att: 50, def: 80, spa: 95, spd: 90, spe: 65),
    ability: Ability.levitate,
    ability2: null,
    hiddenAbility: null,
    moves: chimechoMoves,
    mega: Pokemon(
      id: 358,
      type1: Type.psychic,
      type2: Type.steel,
      stats: Stats(hp: 75, att: 50, def: 110, spa: 135, spd: 120, spe: 65),
      ability: Ability.levitate,
      moves: chimechoMoves,
      form: 'Mega',
    ),
  ),

  'absol': Pokemon(
    id: 359,
    type1: Type.dark,
    type2: null,
    stats: Stats(hp: 65, att: 130, def: 60, spa: 75, spd: 60, spe: 75),
    ability: Ability.pressure,
    ability2: Ability.superLuck,
    hiddenAbility: Ability.justified,
    moves: absolMoves,
    mega: Pokemon(
      id: 359,
      type1: Type.dark,
      type2: null,
      stats: Stats(hp: 65, att: 150, def: 60, spa: 115, spd: 60, spe: 115),
      ability: Ability.magicBounce,
      ability2: null,
      hiddenAbility: null,
      moves: absolMoves,
      form: 'Mega',
    ),
  ),

  'glalie': Pokemon(
    id: 362,
    type1: Type.ice,
    type2: null,
    stats: Stats(hp: 80, att: 80, def: 80, spa: 80, spd: 80, spe: 80),
    ability: Ability.innerFocus,
    ability2: Ability.iceBody,
    hiddenAbility: Ability.moody,
    moves: glalieMoves,
    mega: Pokemon(
      id: 362,
      type1: Type.ice,
      type2: null,
      stats: Stats(hp: 80, att: 120, def: 80, spa: 120, spd: 80, spe: 100),
      ability: Ability.refrigerate,
      ability2: null,
      hiddenAbility: null,
      moves: glalieMoves,
      form: 'Mega',
    ),
  ),

  'torterra': Pokemon(
    id: 389,
    type1: Type.grass,
    type2: Type.ground,
    stats: Stats(hp: 95, att: 109, def: 105, spa: 75, spd: 85, spe: 56),
    ability: Ability.overgrow,
    ability2: null,
    hiddenAbility: Ability.shellArmor,
    moves: torterraMoves,
  ),

  'infernape': Pokemon(
    id: 392,
    type1: Type.fire,
    type2: Type.fighting,
    stats: Stats(hp: 76, att: 104, def: 71, spa: 104, spd: 71, spe: 108),
    ability: Ability.blaze,
    ability2: null,
    hiddenAbility: Ability.ironFist,
    moves: infernapeMoves,
  ),

  'empoleon': Pokemon(
    id: 395,
    type1: Type.water,
    type2: Type.steel,
    stats: Stats(hp: 84, att: 86, def: 88, spa: 111, spd: 101, spe: 60),
    ability: Ability.torrent,
    ability2: null,
    hiddenAbility: Ability.defiant,
    moves: empoleonMoves,
  ),

  'luxray': Pokemon(
    id: 405,
    type1: Type.electric,
    type2: null,
    stats: Stats(hp: 80, att: 120, def: 79, spa: 95, spd: 79, spe: 70),
    ability: Ability.rivalry,
    ability2: Ability.intimidate,
    hiddenAbility: Ability.guts,
    moves: luxrayMoves,
  ),
  'roserade': Pokemon(
    id: 407,
    type1: Type.grass,
    type2: Type.poison,
    stats: Stats(hp: 60, att: 70, def: 65, spa: 125, spd: 105, spe: 90),
    ability: Ability.naturalCure,
    ability2: Ability.poisonPoint,
    hiddenAbility: Ability.technician,
    moves: roseradeMoves,
  ),

  'rampardos': Pokemon(
    id: 409,
    type1: Type.rock,
    type2: null,
    stats: Stats(hp: 97, att: 165, def: 60, spa: 65, spd: 50, spe: 58),
    ability: Ability.moldBreaker,
    ability2: Ability.sheerForce,
    hiddenAbility: Ability.sheerForce,
    moves: rampardosMoves,
  ),

  'bastiodon': Pokemon(
    id: 411,
    type1: Type.rock,
    type2: Type.steel,
    stats: Stats(hp: 60, att: 52, def: 168, spa: 47, spd: 138, spe: 30),
    ability: Ability.sturdy,
    ability2: null,
    hiddenAbility: Ability.soundproof,
    moves: bastiodonMoves,
  ),

  'lopunny': Pokemon(
    id: 428,
    type1: Type.normal,
    type2: null,
    stats: Stats(hp: 65, att: 76, def: 84, spa: 54, spd: 96, spe: 105),
    ability: Ability.cuteCharm,
    ability2: Ability.klutz,
    hiddenAbility: Ability.limber,
    moves: lopunnyMoves,
    mega: Pokemon(
      id: 428,
      type1: Type.normal,
      type2: Type.fighting,
      stats: Stats(hp: 65, att: 136, def: 94, spa: 54, spd: 96, spe: 135),
      ability: Ability.scrappy,
      ability2: null,
      hiddenAbility: null,
      moves: lopunnyMoves,
      form: 'Mega',
    ),
  ),

  'spiritomb': Pokemon(
    id: 442,
    type1: Type.ghost,
    type2: Type.dark,
    stats: Stats(hp: 50, att: 92, def: 108, spa: 92, spd: 108, spe: 35),
    ability: Ability.pressure,
    ability2: null,
    hiddenAbility: Ability.infiltrator,
    moves: spiritombMoves,
  ),

  'garchomp': Pokemon(
    id: 445,
    type1: Type.dragon,
    type2: Type.ground,
    stats: Stats(hp: 108, att: 130, def: 95, spa: 80, spd: 85, spe: 102),
    ability: Ability.sandVeil,
    ability2: null,
    hiddenAbility: Ability.roughSkin,
    moves: garchompMoves,
    mega: Pokemon(
      id: 445,
      type1: Type.dragon,
      type2: Type.ground,
      stats: Stats(hp: 108, att: 170, def: 115, spa: 120, spd: 95, spe: 92),
      ability: Ability.sandForce,
      ability2: null,
      hiddenAbility: null,
      moves: garchompMoves,
      form: 'Mega',
    ),
  ),

  'lucario': Pokemon(
    id: 448,
    type1: Type.fighting,
    type2: Type.steel,
    stats: Stats(hp: 70, att: 110, def: 70, spa: 115, spd: 70, spe: 90),
    ability: Ability.steadfast,
    ability2: Ability.innerFocus,
    hiddenAbility: Ability.justified,
    moves: lucarioMoves,
    mega: Pokemon(
      id: 448,
      type1: Type.fighting,
      type2: Type.steel,
      stats: Stats(hp: 70, att: 145, def: 88, spa: 140, spd: 70, spe: 112),
      ability: Ability.adaptability,
      ability2: null,
      hiddenAbility: null,
      moves: lucarioMoves,
      form: 'Mega',
    ),
  ),

  'hippowdon': Pokemon(
    id: 450,
    type1: Type.ground,
    type2: null,
    stats: Stats(hp: 108, att: 112, def: 118, spa: 68, spd: 72, spe: 47),
    ability: Ability.sandStream,
    ability2: null,
    hiddenAbility: Ability.sandForce,
    moves: hippowdonMoves,
  ),

  'toxicroak': Pokemon(
    id: 454,
    type1: Type.poison,
    type2: Type.fighting,
    stats: Stats(hp: 83, att: 106, def: 65, spa: 86, spd: 65, spe: 85),
    ability: Ability.anticipation,
    ability2: Ability.drySkin,
    hiddenAbility: Ability.poisonTouch,
    moves: toxicroakMoves,
  ),

  'abomasnow': Pokemon(
    id: 460,
    type1: Type.grass,
    type2: Type.ice,
    stats: Stats(hp: 90, att: 92, def: 75, spa: 92, spd: 85, spe: 60),
    ability: Ability.snowWarning,
    ability2: null,
    hiddenAbility: Ability.soundproof,
    moves: abomasnowMoves,
    mega: Pokemon(
      id: 460,
      type1: Type.grass,
      type2: Type.ice,
      stats: Stats(hp: 90, att: 132, def: 105, spa: 132, spd: 105, spe: 30),
      ability: Ability.snowWarning,
      ability2: null,
      hiddenAbility: null,
      moves: abomasnowMoves,
      form: 'Mega',
    ),
  ),

  'weavile': Pokemon(
    id: 461,
    type1: Type.dark,
    type2: Type.ice,
    stats: Stats(hp: 70, att: 120, def: 65, spa: 45, spd: 85, spe: 125),
    ability: Ability.pressure,
    ability2: Ability.pickpocket,
    hiddenAbility: Ability.pickpocket,
    moves: weavileMoves,
  ),

  'rhyperior': Pokemon(
    id: 464,
    type1: Type.ground,
    type2: Type.rock,
    stats: Stats(hp: 115, att: 140, def: 130, spa: 55, spd: 55, spe: 40),
    ability: Ability.lightningRod,
    ability2: Ability.solidRock,
    hiddenAbility: Ability.reckless,
    moves: rhyperiorMoves,
  ),

  'leafeon': Pokemon(
    id: 470,
    type1: Type.grass,
    type2: null,
    stats: Stats(hp: 65, att: 110, def: 130, spa: 60, spd: 65, spe: 95),
    ability: Ability.leafGuard,
    ability2: null,
    hiddenAbility: Ability.chlorophyll,
    moves: leafeonMoves,
  ),

  'glaceon': Pokemon(
    id: 471,
    type1: Type.ice,
    type2: null,
    stats: Stats(hp: 65, att: 60, def: 110, spa: 130, spd: 95, spe: 65),
    ability: Ability.snowCloak,
    ability2: null,
    hiddenAbility: Ability.iceBody,
    moves: glaceonMoves,
  ),

  'gliscor': Pokemon(
    id: 472,
    type1: Type.ground,
    type2: Type.flying,
    stats: Stats(hp: 75, att: 95, def: 125, spa: 45, spd: 75, spe: 95),
    ability: Ability.hyperCutter,
    ability2: Ability.sandVeil,
    hiddenAbility: Ability.poisonHeal,
    moves: gliscorMoves,
  ),

  'mamoswine': Pokemon(
    id: 473,
    type1: Type.ice,
    type2: Type.ground,
    stats: Stats(hp: 110, att: 130, def: 80, spa: 70, spd: 60, spe: 80),
    ability: Ability.oblivious,
    ability2: Ability.snowCloak,
    hiddenAbility: Ability.thickFat,
    moves: mamoswineMoves,
  ),

  'gallade': Pokemon(
    id: 475,
    type1: Type.psychic,
    type2: Type.fighting,
    stats: Stats(hp: 68, att: 125, def: 65, spa: 65, spd: 115, spe: 80),
    ability: Ability.steadfast,
    ability2: null,
    hiddenAbility: Ability.justified,
    moves: galladeMoves,
    mega: Pokemon(
      id: 475,
      type1: Type.psychic,
      type2: Type.fighting,
      stats: Stats(hp: 68, att: 165, def: 95, spa: 65, spd: 115, spe: 110),
      ability: Ability.innerFocus,
      ability2: null,
      hiddenAbility: null,
      moves: galladeMoves,
      form: 'Mega',
    ),
  ),

  'froslass': Pokemon(
    id: 478,
    type1: Type.ice,
    type2: Type.ghost,
    stats: Stats(hp: 70, att: 80, def: 70, spa: 80, spd: 70, spe: 110),
    ability: Ability.snowCloak,
    ability2: null,
    hiddenAbility: Ability.cursedBody,
    moves: froslassMoves,
    mega: Pokemon(
      id: 478,
      type1: Type.ice,
      type2: Type.ghost,
      stats: Stats(hp: 70, att: 80, def: 70, spa: 140, spd: 100, spe: 120),
      ability: Ability.snowWarning,
      moves: froslassMoves,
      form: 'Mega',
    ),
  ),

  'rotom': Pokemon(
    id: 479,
    type1: Type.electric,
    type2: Type.ghost,
    stats: Stats(hp: 50, att: 50, def: 77, spa: 95, spd: 77, spe: 91),
    ability: Ability.levitate,
    ability2: null,
    hiddenAbility: null,
    moves: rotomMoves,
  ),

  'rotom (Heat)': Pokemon(
    id: 479,
    type1: Type.electric,
    type2: Type.fire,
    stats: Stats(hp: 50, att: 65, def: 107, spa: 105, spd: 107, spe: 86),
    ability: Ability.levitate,
    ability2: null,
    hiddenAbility: null,
    moves: rotomHeatMoves,
    form: 'Heat',
  ),

  'rotom (Wash)': Pokemon(
    id: 479,
    type1: Type.electric,
    type2: Type.water,
    stats: Stats(hp: 50, att: 65, def: 107, spa: 105, spd: 107, spe: 86),
    ability: Ability.levitate,
    ability2: null,
    hiddenAbility: null,
    moves: rotomWashMoves,
    form: 'Wash',
  ),

  'rotom (Frost)': Pokemon(
    id: 479,
    type1: Type.electric,
    type2: Type.ice,
    stats: Stats(hp: 50, att: 65, def: 107, spa: 105, spd: 107, spe: 86),
    ability: Ability.levitate,
    ability2: null,
    hiddenAbility: null,
    moves: rotomFrostMoves,
    form: 'Frost',
  ),

  'rotom (Fan)': Pokemon(
    id: 479,
    type1: Type.electric,
    type2: Type.flying,
    stats: Stats(hp: 50, att: 65, def: 107, spa: 105, spd: 107, spe: 86),
    ability: Ability.levitate,
    ability2: null,
    hiddenAbility: null,
    moves: rotomFanMoves,
    form: 'Fan',
  ),

  'rotom (Mow)': Pokemon(
    id: 479,
    type1: Type.electric,
    type2: Type.grass,
    stats: Stats(hp: 50, att: 65, def: 107, spa: 105, spd: 107, spe: 86),
    ability: Ability.levitate,
    ability2: null,
    hiddenAbility: null,
    moves: rotomMowMoves,
    form: 'Mow',
  ),

  'serperior': Pokemon(
    id: 497,
    type1: Type.grass,
    type2: null,
    stats: Stats(hp: 75, att: 75, def: 95, spa: 75, spd: 95, spe: 113),
    ability: Ability.overgrow,
    ability2: null,
    hiddenAbility: Ability.contrary,
    moves: serperiorMoves,
  ),
  'emboar': Pokemon(
    id: 500,
    type1: Type.fire,
    type2: Type.fighting,
    stats: Stats(hp: 110, att: 123, def: 65, spa: 100, spd: 65, spe: 65),
    ability: Ability.blaze,
    ability2: null,
    hiddenAbility: Ability.reckless,
    moves: emboarMoves,
    mega: Pokemon(
      id: 500,
      type1: Type.fire,
      type2: Type.fighting,
      stats: Stats(hp: 110, att: 148, def: 75, spa: 110, spd: 110, spe: 75),
      ability: Ability.moldBreaker,
      moves: emboarMoves,
      form: 'Mega',
    ),
  ),

  'samurott': Pokemon(
    id: 503,
    type1: Type.water,
    type2: null,
    stats: Stats(hp: 95, att: 100, def: 85, spa: 108, spd: 70, spe: 70),
    ability: Ability.torrent,
    ability2: null,
    hiddenAbility: Ability.shellArmor,
    moves: samurottMoves,
  ),

  'samurott (Hisui)': Pokemon(
    id: 503,
    type1: Type.water,
    type2: Type.dark,
    stats: Stats(hp: 90, att: 108, def: 80, spa: 100, spd: 65, spe: 85),
    ability: Ability.torrent,
    ability2: null,
    hiddenAbility: Ability.sharpness,
    moves: samurottHisuiMoves,
    form: 'Hisui',
  ),

  'watchog': Pokemon(
    id: 505,
    type1: Type.normal,
    type2: null,
    stats: Stats(hp: 60, att: 85, def: 69, spa: 60, spd: 69, spe: 77),
    ability: Ability.illuminate,
    ability2: Ability.keenEye,
    hiddenAbility: Ability.analytic,
    moves: watchogMoves,
  ),

  'liepard': Pokemon(
    id: 510,
    type1: Type.dark,
    type2: null,
    stats: Stats(hp: 64, att: 88, def: 50, spa: 88, spd: 50, spe: 106),
    ability: Ability.limber,
    ability2: Ability.unburden,
    hiddenAbility: Ability.prankster,
    moves: liepardMoves,
  ),

  'simisage': Pokemon(
    id: 512,
    type1: Type.grass,
    type2: null,
    stats: Stats(hp: 75, att: 98, def: 63, spa: 98, spd: 63, spe: 101),
    ability: Ability.gluttony,
    ability2: null,
    hiddenAbility: Ability.overgrow,
    moves: simisageMoves,
  ),

  'simisear': Pokemon(
    id: 514,
    type1: Type.fire,
    type2: null,
    stats: Stats(hp: 75, att: 98, def: 63, spa: 98, spd: 63, spe: 101),
    ability: Ability.gluttony,
    ability2: null,
    hiddenAbility: Ability.blaze,
    moves: simisearMoves,
  ),

  'simipour': Pokemon(
    id: 516,
    type1: Type.water,
    type2: null,
    stats: Stats(hp: 75, att: 98, def: 63, spa: 98, spd: 63, spe: 101),
    ability: Ability.gluttony,
    ability2: null,
    hiddenAbility: Ability.torrent,
    moves: simipourMoves,
  ),

  'excadrill': Pokemon(
    id: 530,
    type1: Type.ground,
    type2: Type.steel,
    stats: Stats(hp: 110, att: 135, def: 60, spa: 50, spd: 65, spe: 88),
    ability: Ability.sandRush,
    ability2: Ability.sandForce,
    hiddenAbility: Ability.moldBreaker,
    moves: excadrillMoves,
    mega: Pokemon(
      id: 530,
      type1: Type.ground,
      type2: Type.steel,
      stats: Stats(hp: 110, att: 165, def: 100, spa: 65, spd: 65, spe: 103),
      ability: Ability.piercingDrill,
      moves: excadrillMoves,
      form: 'Mega',
    ),
  ),

  'audino': Pokemon(
    id: 531,
    type1: Type.normal,
    type2: null,
    stats: Stats(hp: 103, att: 60, def: 86, spa: 60, spd: 86, spe: 50),
    ability: Ability.healer,
    ability2: Ability.regenerator,
    hiddenAbility: Ability.klutz,
    moves: audinoMoves,
    mega2: Pokemon(
      id: 531,
      type1: Type.normal,
      type2: Type.fairy,
      stats: Stats(hp: 103, att: 60, def: 126, spa: 80, spd: 126, spe: 50),
      ability: Ability.healer,
      ability2: null,
      hiddenAbility: null,
      moves: audinoMoves,
      form: 'Mega',
    ),
  ),

  'conkeldurr': Pokemon(
    id: 534,
    type1: Type.fighting,
    type2: null,
    stats: Stats(hp: 105, att: 140, def: 95, spa: 55, spd: 65, spe: 45),
    ability: Ability.guts,
    ability2: Ability.sheerForce,
    hiddenAbility: Ability.ironFist,
    moves: conkeldurrMoves,
  ),

  'whimsicott': Pokemon(
    id: 547,
    type1: Type.grass,
    type2: Type.fairy,
    stats: Stats(hp: 60, att: 67, def: 85, spa: 77, spd: 75, spe: 116),
    ability: Ability.prankster,
    ability2: Ability.infiltrator,
    hiddenAbility: Ability.chlorophyll,
    moves: whimsicottMoves,
  ),

  'krookodile': Pokemon(
    id: 553,
    type1: Type.ground,
    type2: Type.dark,
    stats: Stats(hp: 95, att: 117, def: 80, spa: 65, spd: 70, spe: 92),
    ability: Ability.intimidate,
    ability2: Ability.moxie,
    hiddenAbility: Ability.angerPoint,
    moves: krookodileMoves,
  ),

  'cofagrigus': Pokemon(
    id: 563,
    type1: Type.ghost,
    type2: null,
    stats: Stats(hp: 58, att: 50, def: 145, spa: 95, spd: 105, spe: 30),
    ability: Ability.mummy,
    ability2: null,
    hiddenAbility: null,
    moves: cofagrigusMoves,
  ),

  'garbodor': Pokemon(
    id: 569,
    type1: Type.poison,
    type2: null,
    stats: Stats(hp: 80, att: 95, def: 82, spa: 60, spd: 82, spe: 75),
    ability: Ability.stench,
    ability2: Ability.weakArmor,
    hiddenAbility: Ability.aftermath,
    moves: garbodorMoves,
  ),

  'zoroark': Pokemon(
    id: 571,
    type1: Type.dark,
    type2: null,
    stats: Stats(hp: 60, att: 105, def: 60, spa: 120, spd: 60, spe: 105),
    ability: Ability.illusion,
    ability2: null,
    hiddenAbility: null,
    moves: zoroarkMoves,
  ),

  'zoroark (Hisui)': Pokemon(
    id: 571,
    type1: Type.normal,
    type2: Type.ghost,
    stats: Stats(hp: 55, att: 100, def: 60, spa: 125, spd: 60, spe: 110),
    ability: Ability.illusion,
    ability2: null,
    hiddenAbility: null,
    moves: zoroarkHisuiMoves,
    form: 'Hisui',
  ),

  'reuniclus': Pokemon(
    id: 579,
    type1: Type.psychic,
    type2: null,
    stats: Stats(hp: 110, att: 65, def: 75, spa: 125, spd: 85, spe: 30),
    ability: Ability.overcoat,
    ability2: Ability.magicGuard,
    hiddenAbility: Ability.regenerator,
    moves: reuniclusMoves,
  ),

  'vanilluxe': Pokemon(
    id: 584,
    type1: Type.ice,
    type2: null,
    stats: Stats(hp: 71, att: 95, def: 85, spa: 110, spd: 95, spe: 79),
    ability: Ability.iceBody,
    ability2: Ability.snowWarning,
    hiddenAbility: Ability.weakArmor,
    moves: vanilluxeMoves,
  ),

  'emolga': Pokemon(
    id: 587,
    type1: Type.electric,
    type2: Type.flying,
    stats: Stats(hp: 55, att: 75, def: 60, spa: 75, spd: 60, spe: 103),
    ability: Ability.static,
    ability2: null,
    hiddenAbility: Ability.motorDrive,
    moves: emolgaMoves,
  ),

  'chandelure': Pokemon(
    id: 609,
    type1: Type.ghost,
    type2: Type.fire,
    stats: Stats(hp: 60, att: 55, def: 90, spa: 145, spd: 90, spe: 80),
    ability: Ability.flashFire,
    ability2: Ability.flameBody,
    hiddenAbility: Ability.infiltrator,
    moves: chandelureMoves,
    mega: Pokemon(
      id: 609,
      type1: Type.ghost,
      type2: Type.fire,
      stats: Stats(hp: 60, att: 75, def: 110, spa: 175, spd: 110, spe: 90),
      ability: Ability.infiltrator,
      moves: chandelureMoves,
      form: 'Mega',
    ),
  ),

  'beartic': Pokemon(
    id: 614,
    type1: Type.ice,
    type2: null,
    stats: Stats(hp: 95, att: 130, def: 80, spa: 70, spd: 80, spe: 50),
    ability: Ability.snowCloak,
    ability2: Ability.slushRush,
    hiddenAbility: Ability.swiftSwim,
    moves: bearticMoves,
  ),

  'stunfisk': Pokemon(
    id: 618,
    type1: Type.ground,
    type2: Type.electric,
    stats: Stats(hp: 109, att: 66, def: 84, spa: 81, spd: 99, spe: 32),
    ability: Ability.static,
    ability2: Ability.limber,
    hiddenAbility: Ability.sandVeil,
    moves: stunfiskMoves,
  ),

  'stunfisk (Galar)': Pokemon(
    id: 618,
    type1: Type.ground,
    type2: Type.steel,
    stats: Stats(hp: 109, att: 81, def: 99, spa: 66, spd: 84, spe: 32),
    ability: Ability.mimicry,
    ability2: null,
    hiddenAbility: null,
    moves: stunfiskGalarMoves,
    form: 'Galar',
  ),

  'golurk': Pokemon(
    id: 623,
    type1: Type.ground,
    type2: Type.ghost,
    stats: Stats(hp: 89, att: 124, def: 80, spa: 55, spd: 80, spe: 55),
    ability: Ability.ironFist,
    ability2: Ability.klutz,
    hiddenAbility: Ability.noGuard,
    moves: golurkMoves,
    mega: Pokemon(
      id: 623,
      type1: Type.ground,
      type2: Type.ghost,
      stats: Stats(hp: 89, att: 159, def: 105, spa: 70, spd: 105, spe: 55),
      ability: Ability.unseenFist,
      moves: golurkMoves,
      form: 'Mega',
    ),
  ),

  'hydreigon': Pokemon(
    id: 635,
    type1: Type.dark,
    type2: Type.dragon,
    stats: Stats(hp: 92, att: 105, def: 90, spa: 125, spd: 90, spe: 98),
    ability: Ability.levitate,
    ability2: null,
    hiddenAbility: null,
    moves: hydreigonMoves,
  ),

  'volcarona': Pokemon(
    id: 637,
    type1: Type.bug,
    type2: Type.fire,
    stats: Stats(hp: 85, att: 60, def: 65, spa: 135, spd: 105, spe: 100),
    ability: Ability.flameBody,
    ability2: null,
    hiddenAbility: Ability.swarm,
    moves: volcaronaMoves,
  ),

  'chesnaught': Pokemon(
    id: 652,
    type1: Type.grass,
    type2: Type.fighting,
    stats: Stats(hp: 88, att: 107, def: 122, spa: 74, spd: 75, spe: 64),
    ability: Ability.overgrow,
    ability2: null,
    hiddenAbility: Ability.bulletproof,
    moves: chesnaughtMoves,
    mega: Pokemon(
      id: 652,
      type1: Type.grass,
      type2: Type.fighting,
      stats: Stats(hp: 88, att: 137, def: 172, spa: 74, spd: 115, spe: 44),
      ability: Ability.bulletproof,
      moves: chesnaughtMoves,
      form: 'Mega',
    ),
  ),

  'delphox': Pokemon(
    id: 655,
    type1: Type.fire,
    type2: Type.psychic,
    stats: Stats(hp: 75, att: 69, def: 72, spa: 114, spd: 100, spe: 104),
    ability: Ability.blaze,
    ability2: null,
    hiddenAbility: Ability.magician,
    moves: delphoxMoves,
    mega: Pokemon(
      id: 655,
      type1: Type.fire,
      type2: Type.psychic,
      stats: Stats(hp: 75, att: 69, def: 72, spa: 159, spd: 125, spe: 134),
      ability: Ability.levitate,
      moves: delphoxMoves,
      form: 'Mega',
    ),
  ),

  'greninja': Pokemon(
    id: 658,
    type1: Type.water,
    type2: Type.dark,
    stats: Stats(hp: 72, att: 95, def: 67, spa: 103, spd: 71, spe: 122),
    ability: Ability.torrent,
    ability2: null,
    hiddenAbility: Ability.protean,
    moves: greninjaMoves,
    mega: Pokemon(
      id: 658,
      type1: Type.water,
      type2: Type.dark,
      stats: Stats(hp: 72, att: 125, def: 77, spa: 133, spd: 81, spe: 142),
      ability: Ability.protean,
      moves: greninjaMoves,
      form: 'Mega',
    ),
  ),

  'diggersby': Pokemon(
    id: 660,
    type1: Type.normal,
    type2: Type.ground,
    stats: Stats(hp: 85, att: 56, def: 77, spa: 50, spd: 77, spe: 78),
    ability: Ability.pickup,
    ability2: Ability.cheekPouch,
    hiddenAbility: Ability.hugePower,
    moves: diggersbyMoves,
  ),

  'talonflame': Pokemon(
    id: 663,
    type1: Type.fire,
    type2: Type.flying,
    stats: Stats(hp: 78, att: 81, def: 71, spa: 74, spd: 69, spe: 126),
    ability: Ability.flameBody,
    ability2: null,
    hiddenAbility: Ability.galeWings,
    moves: talonflameMoves,
  ),

  'vivillon': Pokemon(
    id: 666,
    type1: Type.bug,
    type2: Type.flying,
    stats: Stats(hp: 80, att: 52, def: 50, spa: 90, spd: 50, spe: 89),
    ability: Ability.shieldDust,
    ability2: Ability.compoundEyes,
    hiddenAbility: Ability.friendGuard,
    moves: vivillonMoves,
  ),
  'floette (Eternal)': Pokemon(
    id: 670,
    type1: Type.fairy,
    type2: null,
    stats: Stats(hp: 74, att: 65, def: 67, spa: 125, spd: 128, spe: 92),
    ability: Ability.flowerVeil,
    ability2: null,
    hiddenAbility: Ability.symbiosis,
    moves: floetteEternalMoves,
    form: 'Eternal',
    mega: Pokemon(
      id: 670,
      type1: Type.fairy,
      type2: null,
      stats: Stats(hp: 74, att: 85, def: 87, spa: 155, spd: 148, spe: 102),
      ability: Ability.fairyAura,
      moves: floetteEternalMoves,
      form: 'Mega',
    ),
  ),

  'florges': Pokemon(
    id: 671,
    type1: Type.fairy,
    type2: null,
    stats: Stats(hp: 78, att: 65, def: 68, spa: 112, spd: 154, spe: 75),
    ability: Ability.flowerVeil,
    ability2: null,
    hiddenAbility: Ability.symbiosis,
    moves: florgesMoves,
  ),

  'pangoro': Pokemon(
    id: 675,
    type1: Type.fighting,
    type2: Type.dark,
    stats: Stats(hp: 95, att: 124, def: 78, spa: 69, spd: 71, spe: 58),
    ability: Ability.ironFist,
    ability2: Ability.moldBreaker,
    hiddenAbility: Ability.scrappy,
    moves: pangoroMoves,
  ),

  'furfrou': Pokemon(
    id: 676,
    type1: Type.normal,
    type2: null,
    stats: Stats(hp: 75, att: 80, def: 60, spa: 65, spd: 90, spe: 102),
    ability: Ability.furCoat,
    ability2: null,
    hiddenAbility: null,
    moves: furfrouMoves,
  ),

  'meowstic': Pokemon(
    id: 678,
    type1: Type.psychic,
    type2: null,
    stats: Stats(hp: 74, att: 48, def: 76, spa: 83, spd: 81, spe: 104),
    ability: Ability.keenEye,
    ability2: Ability.infiltrator,
    hiddenAbility: Ability.prankster,
    moves: meowsticMoves,
    mega: Pokemon(
      id: 678,
      type1: Type.psychic,
      type2: null,
      stats: Stats(hp: 74, att: 48, def: 76, spa: 143, spd: 101, spe: 124),
      ability: Ability.trace,
      moves: meowsticMoves,
      form: 'Mega',
    ),
  ),

  'meowstic (Female)': Pokemon(
    id: 678,
    type1: Type.psychic,
    type2: null,
    stats: Stats(hp: 74, att: 48, def: 76, spa: 83, spd: 81, spe: 104),
    ability: Ability.keenEye,
    ability2: Ability.infiltrator,
    hiddenAbility: Ability.competitive,
    moves: meowsticFemaleMoves,
    form: 'Female',
    mega: Pokemon(
      id: 678,
      type1: Type.psychic,
      type2: null,
      stats: Stats(hp: 74, att: 48, def: 76, spa: 143, spd: 101, spe: 124),
      ability: Ability.trace,
      moves: meowsticFemaleMoves,
      form: 'Mega',
    ),
  ),

  'aegislash': Pokemon(
    id: 681,
    type1: Type.steel,
    type2: Type.ghost,
    stats: Stats(hp: 60, att: 50, def: 140, spa: 50, spd: 140, spe: 60),
    ability: Ability.stanceChange,
    ability2: null,
    hiddenAbility: null,
    moves: aegislashMoves,
  ),

  'aromatisse': Pokemon(
    id: 683,
    type1: Type.fairy,
    type2: null,
    stats: Stats(hp: 101, att: 72, def: 72, spa: 99, spd: 89, spe: 29),
    ability: Ability.healer,
    ability2: null,
    hiddenAbility: Ability.aromaVeil,
    moves: aromatisseMoves,
  ),

  'slurpuff': Pokemon(
    id: 685,
    type1: Type.fairy,
    type2: null,
    stats: Stats(hp: 82, att: 80, def: 86, spa: 85, spd: 75, spe: 72),
    ability: Ability.sweetVeil,
    ability2: null,
    hiddenAbility: Ability.unburden,
    moves: slurpuffMoves,
  ),

  'clawitzer': Pokemon(
    id: 693,
    type1: Type.water,
    type2: null,
    stats: Stats(hp: 71, att: 73, def: 88, spa: 120, spd: 89, spe: 59),
    ability: Ability.megaLauncher,
    ability2: null,
    hiddenAbility: null,
    moves: clawitzerMoves,
  ),

  'heliolisk': Pokemon(
    id: 695,
    type1: Type.electric,
    type2: Type.normal,
    stats: Stats(hp: 62, att: 55, def: 52, spa: 109, spd: 94, spe: 109),
    ability: Ability.drySkin,
    ability2: Ability.sandVeil,
    hiddenAbility: Ability.solarPower,
    moves: helioliskMoves,
  ),

  'tyrantrum': Pokemon(
    id: 697,
    type1: Type.rock,
    type2: Type.dragon,
    stats: Stats(hp: 82, att: 121, def: 119, spa: 69, spd: 59, spe: 71),
    ability: Ability.strongJaw,
    ability2: null,
    hiddenAbility: Ability.rockHead,
    moves: tyrantrumMoves,
  ),
  'aurorus': Pokemon(
    id: 699,
    type1: Type.rock,
    type2: Type.ice,
    stats: Stats(hp: 123, att: 77, def: 72, spa: 99, spd: 92, spe: 58),
    ability: Ability.refrigerate,
    ability2: null,
    hiddenAbility: Ability.snowWarning,
    moves: aurorusMoves,
  ),

  'sylveon': Pokemon(
    id: 700,
    type1: Type.fairy,
    type2: null,
    stats: Stats(hp: 95, att: 65, def: 65, spa: 110, spd: 130, spe: 60),
    ability: Ability.cuteCharm,
    ability2: null,
    hiddenAbility: Ability.pixilate,
    moves: sylveonMoves,
  ),

  'hawlucha': Pokemon(
    id: 701,
    type1: Type.fighting,
    type2: Type.flying,
    stats: Stats(hp: 78, att: 92, def: 75, spa: 74, spd: 63, spe: 118),
    ability: Ability.limber,
    ability2: Ability.unburden,
    hiddenAbility: Ability.moldBreaker,
    moves: hawluchaMoves,
    mega: Pokemon(
      id: 701,
      type1: Type.fighting,
      type2: Type.flying,
      stats: Stats(hp: 78, att: 137, def: 100, spa: 74, spd: 93, spe: 118),
      ability: Ability.noGuard,
      moves: hawluchaMoves,
      form: 'Mega',
    ),
  ),

  'dedenne': Pokemon(
    id: 702,
    type1: Type.electric,
    type2: Type.fairy,
    stats: Stats(hp: 67, att: 58, def: 57, spa: 81, spd: 67, spe: 101),
    ability: Ability.cheekPouch,
    ability2: Ability.pickup,
    hiddenAbility: Ability.plus,
    moves: dedenneMoves,
  ),

  'goodra': Pokemon(
    id: 706,
    type1: Type.dragon,
    type2: null,
    stats: Stats(hp: 90, att: 100, def: 70, spa: 110, spd: 150, spe: 80),
    ability: Ability.sapSipper,
    ability2: Ability.hydration,
    hiddenAbility: Ability.gooey,
    moves: goodraMoves,
  ),

  'goodra (Hisui)': Pokemon(
    id: 706,
    type1: Type.dragon,
    type2: Type.steel,
    stats: Stats(hp: 80, att: 100, def: 100, spa: 110, spd: 150, spe: 60),
    ability: Ability.sapSipper,
    ability2: Ability.overcoat,
    hiddenAbility: Ability.gooey,
    moves: goodraHisuiMoves,
    form: 'Hisui',
  ),

  'klefki': Pokemon(
    id: 707,
    type1: Type.steel,
    type2: Type.fairy,
    stats: Stats(hp: 57, att: 80, def: 91, spa: 80, spd: 87, spe: 75),
    ability: Ability.prankster,
    ability2: null,
    hiddenAbility: Ability.magician,
    moves: klefkiMoves,
  ),

  'trevenant': Pokemon(
    id: 709,
    type1: Type.ghost,
    type2: Type.grass,
    stats: Stats(hp: 85, att: 110, def: 76, spa: 65, spd: 82, spe: 56),
    ability: Ability.naturalCure,
    ability2: Ability.frisk,
    hiddenAbility: Ability.harvest,
    moves: trevenantMoves,
  ),

  'gourgeist': Pokemon(
    id: 711,
    type1: Type.ghost,
    type2: Type.grass,
    stats: Stats(hp: 65, att: 90, def: 122, spa: 58, spd: 75, spe: 84),
    ability: Ability.pickup,
    ability2: Ability.frisk,
    hiddenAbility: Ability.insomnia,
    moves: gourgeistMoves,
  ),

  'avalugg': Pokemon(
    id: 713,
    type1: Type.ice,
    type2: null,
    stats: Stats(hp: 95, att: 117, def: 184, spa: 44, spd: 46, spe: 28),
    ability: Ability.ownTempo,
    ability2: Ability.iceBody,
    hiddenAbility: Ability.sturdy,
    moves: avaluggMoves,
  ),

  'avalugg (Hisui)': Pokemon(
    id: 713,
    type1: Type.ice,
    type2: Type.rock,
    stats: Stats(hp: 95, att: 127, def: 184, spa: 34, spd: 36, spe: 38),
    ability: Ability.strongJaw,
    ability2: Ability.iceBody,
    hiddenAbility: Ability.sturdy,
    moves: avaluggHisuiMoves,
    form: 'Hisui',
  ),

  'noivern': Pokemon(
    id: 715,
    type1: Type.flying,
    type2: Type.dragon,
    stats: Stats(hp: 85, att: 70, def: 80, spa: 97, spd: 80, spe: 123),
    ability: Ability.frisk,
    ability2: Ability.infiltrator,
    hiddenAbility: Ability.telepathy,
    moves: noivernMoves,
  ),

  'decidueye': Pokemon(
    id: 724,
    type1: Type.grass,
    type2: Type.ghost,
    stats: Stats(hp: 78, att: 107, def: 75, spa: 100, spd: 100, spe: 70),
    ability: Ability.overgrow,
    ability2: null,
    hiddenAbility: Ability.longReach,
    moves: decidueyeMoves,
  ),

  'decidueye (Hisui)': Pokemon(
    id: 724,
    type1: Type.grass,
    type2: Type.fighting,
    stats: Stats(hp: 88, att: 112, def: 80, spa: 95, spd: 95, spe: 60),
    ability: Ability.overgrow,
    ability2: null,
    hiddenAbility: Ability.scrappy,
    moves: decidueyeHisuiMoves,
    form: 'Hisui',
  ),

  'incineroar': Pokemon(
    id: 727,
    type1: Type.fire,
    type2: Type.dark,
    stats: Stats(hp: 95, att: 115, def: 90, spa: 80, spd: 90, spe: 60),
    ability: Ability.blaze,
    ability2: null,
    hiddenAbility: Ability.intimidate,
    moves: incineroarMoves,
  ),

  'primarina': Pokemon(
    id: 730,
    type1: Type.water,
    type2: Type.fairy,
    stats: Stats(hp: 80, att: 74, def: 74, spa: 126, spd: 116, spe: 60),
    ability: Ability.torrent,
    ability2: null,
    hiddenAbility: Ability.liquidVoice,
    moves: primarinaMoves,
  ),

  'toucannon': Pokemon(
    id: 733,
    type1: Type.normal,
    type2: Type.flying,
    stats: Stats(hp: 80, att: 120, def: 75, spa: 75, spd: 75, spe: 60),
    ability: Ability.keenEye,
    ability2: Ability.skillLink,
    hiddenAbility: Ability.sheerForce,
    moves: toucannonMoves,
  ),

  'crabominable': Pokemon(
    id: 740,
    type1: Type.fighting,
    type2: Type.ice,
    stats: Stats(hp: 97, att: 132, def: 77, spa: 62, spd: 67, spe: 43),
    ability: Ability.hyperCutter,
    ability2: Ability.ironFist,
    hiddenAbility: Ability.angerPoint,
    moves: crabominableMoves,
    mega: Pokemon(
      id: 740,
      type1: Type.fighting,
      type2: Type.ice,
      stats: Stats(hp: 97, att: 157, def: 122, spa: 62, spd: 107, spe: 33),
      ability: Ability.ironFist,
      moves: crabominableMoves,
      form: 'Mega',
    ),
  ),

  'lycanroc': Pokemon(
    id: 745,
    type1: Type.rock,
    type2: null,
    stats: Stats(hp: 75, att: 115, def: 65, spa: 55, spd: 65, spe: 112),
    ability: Ability.keenEye,
    ability2: Ability.sandRush,
    hiddenAbility: Ability.steadfast,
    moves: lycanrocMoves,
  ),

  'lycanroc (Midnight)': Pokemon(
    id: 745,
    type1: Type.rock,
    type2: null,
    stats: Stats(hp: 85, att: 115, def: 75, spa: 55, spd: 75, spe: 82),
    ability: Ability.keenEye,
    ability2: Ability.vitalSpirit,
    hiddenAbility: Ability.noGuard,
    moves: lycanrocMidnightMoves,
    form: 'Midnight',
  ),

  'lycanroc (Dusk)': Pokemon(
    id: 745,
    type1: Type.rock,
    type2: null,
    stats: Stats(hp: 75, att: 117, def: 65, spa: 55, spd: 65, spe: 110),
    ability: Ability.toughClaws,
    ability2: null,
    hiddenAbility: null,
    moves: lycanrocDuskMoves,
    form: 'Dusk',
  ),

  'toxapex': Pokemon(
    id: 748,
    type1: Type.poison,
    type2: Type.water,
    stats: Stats(hp: 50, att: 63, def: 152, spa: 53, spd: 142, spe: 35),
    ability: Ability.merciless,
    ability2: Ability.limber,
    hiddenAbility: Ability.regenerator,
    moves: toxapexMoves,
  ),

  'mudsdale': Pokemon(
    id: 750,
    type1: Type.ground,
    type2: null,
    stats: Stats(hp: 100, att: 125, def: 100, spa: 55, spd: 85, spe: 35),
    ability: Ability.ownTempo,
    ability2: Ability.stamina,
    hiddenAbility: Ability.innerFocus,
    moves: mudsdaleMoves,
  ),

  'araquanid': Pokemon(
    id: 752,
    type1: Type.water,
    type2: Type.bug,
    stats: Stats(hp: 68, att: 70, def: 92, spa: 50, spd: 132, spe: 42),
    ability: Ability.waterBubble,
    ability2: null,
    hiddenAbility: Ability.waterAbsorb,
    moves: araquanidMoves,
  ),

  'salazzle': Pokemon(
    id: 758,
    type1: Type.poison,
    type2: Type.fire,
    stats: Stats(hp: 68, att: 64, def: 60, spa: 111, spd: 60, spe: 117),
    ability: Ability.corrosion,
    ability2: null,
    hiddenAbility: Ability.oblivious,
    moves: salazzleMoves,
  ),

  'tsareena': Pokemon(
    id: 763,
    type1: Type.grass,
    type2: null,
    stats: Stats(hp: 72, att: 120, def: 98, spa: 50, spd: 98, spe: 72),
    ability: Ability.leafGuard,
    ability2: Ability.queenlyMajesty,
    hiddenAbility: Ability.sweetVeil,
    moves: tsareenaMoves,
  ),
  'oranguru': Pokemon(
    id: 765,
    type1: Type.normal,
    type2: Type.psychic,
    stats: Stats(hp: 90, att: 60, def: 80, spa: 90, spd: 110, spe: 60),
    ability: Ability.innerFocus,
    ability2: Ability.telepathy,
    hiddenAbility: Ability.symbiosis,
    moves: oranguruMoves,
  ),

  'passimian': Pokemon(
    id: 766,
    type1: Type.fighting,
    type2: null,
    stats: Stats(hp: 100, att: 120, def: 90, spa: 40, spd: 60, spe: 80),
    ability: Ability.receiver,
    ability2: null,
    hiddenAbility: Ability.defiant,
    moves: passimianMoves,
  ),

  'mimikyu': Pokemon(
    id: 778,
    type1: Type.ghost,
    type2: Type.fairy,
    stats: Stats(hp: 55, att: 90, def: 80, spa: 50, spd: 105, spe: 96),
    ability: Ability.disguise,
    ability2: null,
    hiddenAbility: null,
    moves: mimikyuMoves,
  ),

  'drampa': Pokemon(
    id: 780,
    type1: Type.normal,
    type2: Type.dragon,
    stats: Stats(hp: 78, att: 60, def: 85, spa: 135, spd: 91, spe: 36),
    ability: Ability.berserk,
    ability2: Ability.sapSipper,
    hiddenAbility: Ability.cloudNine,
    moves: drampaMoves,
    mega: Pokemon(
      id: 780,
      type1: Type.normal,
      type2: Type.dragon,
      stats: Stats(hp: 78, att: 85, def: 110, spa: 160, spd: 116, spe: 36),
      ability: Ability.berserk,
      moves: drampaMoves,
      form: 'Mega',
    ),
  ),

  'kommo-o': Pokemon(
    id: 784,
    type1: Type.dragon,
    type2: Type.fighting,
    stats: Stats(hp: 75, att: 110, def: 125, spa: 100, spd: 105, spe: 85),
    ability: Ability.bulletproof,
    ability2: Ability.soundproof,
    hiddenAbility: Ability.overcoat,
    moves: kommoOMoves,
  ),

  'corviknight': Pokemon(
    id: 823,
    type1: Type.flying,
    type2: Type.steel,
    stats: Stats(hp: 98, att: 87, def: 105, spa: 53, spd: 85, spe: 67),
    ability: Ability.pressure,
    ability2: Ability.unnerve,
    hiddenAbility: Ability.mirrorArmor,
    moves: corviknightMoves,
  ),

  'flapple': Pokemon(
    id: 841,
    type1: Type.grass,
    type2: Type.dragon,
    stats: Stats(hp: 70, att: 110, def: 80, spa: 95, spd: 60, spe: 70),
    ability: Ability.ripen,
    ability2: Ability.gluttony,
    hiddenAbility: Ability.hustle,
    moves: flappleMoves,
  ),

  'appletun': Pokemon(
    id: 842,
    type1: Type.grass,
    type2: Type.dragon,
    stats: Stats(hp: 110, att: 85, def: 80, spa: 100, spd: 80, spe: 30),
    ability: Ability.ripen,
    ability2: Ability.gluttony,
    hiddenAbility: Ability.thickFat,
    moves: appletunMoves,
  ),

  'sandaconda': Pokemon(
    id: 844,
    type1: Type.ground,
    stats: Stats(hp: 72, att: 107, def: 125, spa: 65, spd: 70, spe: 71),
    ability: Ability.sandSpit,
    ability2: Ability.shedSkin,
    hiddenAbility: Ability.sandVeil,
    moves: sandacondaMoves,
  ),

  'polteageist': Pokemon(
    id: 855,
    type1: Type.ghost,
    type2: null,
    stats: Stats(hp: 60, att: 65, def: 65, spa: 134, spd: 114, spe: 70),
    ability: Ability.weakArmor,
    ability2: null,
    hiddenAbility: Ability.cursedBody,
    moves: polteageistMoves,
  ),

  'hatterene': Pokemon(
    id: 858,
    type1: Type.psychic,
    type2: Type.fairy,
    stats: Stats(hp: 57, att: 90, def: 95, spa: 136, spd: 103, spe: 29),
    ability: Ability.healer,
    ability2: Ability.anticipation,
    hiddenAbility: Ability.magicBounce,
    moves: hattereneMoves,
  ),

  'mr-rime': Pokemon(
    id: 866,
    type1: Type.ice,
    type2: Type.psychic,
    stats: Stats(hp: 80, att: 85, def: 75, spa: 110, spd: 100, spe: 70),
    ability: Ability.tangledFeet,
    ability2: Ability.screenCleaner,
    hiddenAbility: Ability.iceBody,
    moves: mrRimeMoves,
  ),

  'runerigus': Pokemon(
    id: 867,
    type1: Type.ground,
    type2: Type.ghost,
    stats: Stats(hp: 58, att: 95, def: 145, spa: 50, spd: 105, spe: 30),
    ability: Ability.wanderingSpirit,
    ability2: null,
    hiddenAbility: null,
    moves: runerigusMoves,
  ),

  'alcremie': Pokemon(
    id: 869,
    type1: Type.fairy,
    type2: null,
    stats: Stats(hp: 65, att: 60, def: 75, spa: 110, spd: 121, spe: 64),
    ability: Ability.sweetVeil,
    ability2: null,
    hiddenAbility: Ability.aromaVeil,
    moves: alcremieMoves,
  ),

  'morpeko': Pokemon(
    id: 877,
    type1: Type.electric,
    type2: Type.dark,
    stats: Stats(hp: 58, att: 95, def: 58, spa: 70, spd: 58, spe: 97),
    ability: Ability.hungerSwitch,
    ability2: null,
    hiddenAbility: null,
    moves: morpekoMoves,
  ),

  'dragapult': Pokemon(
    id: 887,
    type1: Type.dragon,
    type2: Type.ghost,
    stats: Stats(hp: 88, att: 120, def: 75, spa: 100, spd: 75, spe: 142),
    ability: Ability.clearBody,
    ability2: Ability.infiltrator,
    hiddenAbility: Ability.cursedBody,
    moves: dragapultMoves,
  ),

  'wyrdeer': Pokemon(
    id: 899,
    type1: Type.normal,
    type2: Type.psychic,
    stats: Stats(hp: 103, att: 105, def: 72, spa: 105, spd: 75, spe: 65),
    ability: Ability.intimidate,
    ability2: Ability.frisk,
    hiddenAbility: Ability.sapSipper,
    moves: wyrdeerMoves,
  ),

  'kleavor': Pokemon(
    id: 900,
    type1: Type.bug,
    type2: Type.rock,
    stats: Stats(hp: 70, att: 135, def: 95, spa: 45, spd: 70, spe: 85),
    ability: Ability.swarm,
    ability2: Ability.sheerForce,
    hiddenAbility: Ability.sharpness,
    moves: kleavorMoves,
  ),

  'basculegion': Pokemon(
    id: 902,
    type1: Type.water,
    type2: Type.ghost,
    stats: Stats(hp: 120, att: 112, def: 65, spa: 80, spd: 75, spe: 78),
    ability: Ability.rattled,
    ability2: Ability.adaptability,
    hiddenAbility: Ability.moldBreaker,
    moves: basculegionMoves,
  ),

  'basculegion (Female)': Pokemon(
    id: 902,
    type1: Type.water,
    type2: Type.ghost,
    stats: Stats(hp: 120, att: 92, def: 65, spa: 100, spd: 75, spe: 78),
    ability: Ability.rattled,
    ability2: Ability.adaptability,
    hiddenAbility: Ability.moldBreaker,
    moves: basculegionFemaleMoves,
    form: 'Female',
  ),

  'sneasler': Pokemon(
    id: 903,
    type1: Type.fighting,
    type2: Type.poison,
    stats: Stats(hp: 80, att: 130, def: 60, spa: 40, spd: 80, spe: 120),
    ability: Ability.pressure,
    ability2: Ability.unburden,
    hiddenAbility: Ability.poisonTouch,
    moves: sneaslerMoves,
  ),

  'meowscarada': Pokemon(
    id: 908,
    type1: Type.grass,
    type2: Type.dark,
    stats: Stats(hp: 76, att: 110, def: 70, spa: 81, spd: 70, spe: 123),
    ability: Ability.overgrow,
    ability2: null,
    hiddenAbility: Ability.protean,
    moves: meowscaradaMoves,
  ),

  'skeledirge': Pokemon(
    id: 911,
    type1: Type.fire,
    type2: Type.ghost,
    stats: Stats(hp: 104, att: 75, def: 100, spa: 110, spd: 75, spe: 66),
    ability: Ability.blaze,
    ability2: null,
    hiddenAbility: Ability.unaware,
    moves: skeledirgeMoves,
  ),

  'quaquaval': Pokemon(
    id: 914,
    type1: Type.water,
    type2: Type.fighting,
    stats: Stats(hp: 85, att: 120, def: 80, spa: 85, spd: 75, spe: 85),
    ability: Ability.torrent,
    ability2: null,
    hiddenAbility: Ability.moxie,
    moves: quaquavalMoves,
  ),

  'maushold': Pokemon(
    id: 925,
    type1: Type.normal,
    type2: null,
    stats: Stats(hp: 74, att: 75, def: 70, spa: 65, spd: 75, spe: 111),
    ability: Ability.friendGuard,
    ability2: Ability.cheekPouch,
    hiddenAbility: Ability.technician,
    moves: mausholdMoves,
  ),

  'garganacl': Pokemon(
    id: 934,
    type1: Type.rock,
    type2: null,
    stats: Stats(hp: 100, att: 100, def: 130, spa: 45, spd: 90, spe: 35),
    ability: Ability.purifyingSalt,
    ability2: Ability.sturdy,
    hiddenAbility: Ability.clearBody,
    moves: garganaclMoves,
  ),

  'armarouge': Pokemon(
    id: 936,
    type1: Type.fire,
    type2: Type.psychic,
    stats: Stats(hp: 85, att: 60, def: 100, spa: 125, spd: 80, spe: 75),
    ability: Ability.flashFire,
    ability2: null,
    hiddenAbility: Ability.weakArmor,
    moves: armarougeMoves,
  ),

  'ceruledge': Pokemon(
    id: 937,
    type1: Type.fire,
    type2: Type.ghost,
    stats: Stats(hp: 75, att: 125, def: 80, spa: 60, spd: 100, spe: 85),
    ability: Ability.flashFire,
    ability2: null,
    hiddenAbility: Ability.weakArmor,
    moves: ceruledgeMoves,
  ),

  'bellibolt': Pokemon(
    id: 939,
    type1: Type.electric,
    type2: null,
    stats: Stats(hp: 109, att: 64, def: 91, spa: 103, spd: 83, spe: 45),
    ability: Ability.electromorphosis,
    ability2: Ability.static,
    hiddenAbility: Ability.damp,
    moves: belliboltMoves,
  ),

  'scovillain': Pokemon(
    id: 952,
    type1: Type.grass,
    type2: Type.fire,
    stats: Stats(hp: 65, att: 108, def: 65, spa: 108, spd: 65, spe: 75),
    ability: Ability.chlorophyll,
    ability2: Ability.insomnia,
    hiddenAbility: Ability.moody,
    moves: scovillainMoves,
    mega: Pokemon(
      id: 952,
      type1: Type.grass,
      type2: Type.fire,
      stats: Stats(hp: 65, att: 138, def: 85, spa: 138, spd: 85, spe: 75),
      ability: Ability.spicySpray,
      moves: scovillainMoves,
      form: 'Mega',
    ),
  ),

  'espathra': Pokemon(
    id: 956,
    type1: Type.psychic,
    type2: null,
    stats: Stats(hp: 95, att: 60, def: 60, spa: 101, spd: 60, spe: 105),
    ability: Ability.opportunist,
    ability2: Ability.frisk,
    hiddenAbility: Ability.speedBoost,
    moves: espathraMoves,
  ),

  'tinkaton': Pokemon(
    id: 959,
    type1: Type.fairy,
    type2: Type.steel,
    stats: Stats(hp: 85, att: 75, def: 77, spa: 70, spd: 105, spe: 94),
    ability: Ability.moldBreaker,
    ability2: Ability.ownTempo,
    hiddenAbility: Ability.pickpocket,
    moves: tinkatonMoves,
  ),

  'palafin': Pokemon(
    id: 964,
    type1: Type.water,
    type2: null,
    stats: Stats(hp: 100, att: 160, def: 97, spa: 106, spd: 87, spe: 100),
    ability: Ability.zeroToHero,
    ability2: null,
    hiddenAbility: null,
    moves: palafinMoves,
  ),

  'orthworm': Pokemon(
    id: 968,
    type1: Type.steel,
    type2: null,
    stats: Stats(hp: 70, att: 85, def: 145, spa: 60, spd: 55, spe: 65),
    ability: Ability.earthEater,
    ability2: null,
    hiddenAbility: Ability.sandVeil,
    moves: orthwormMoves,
  ),

  'glimmora': Pokemon(
    id: 970,
    type1: Type.rock,
    type2: Type.poison,
    stats: Stats(hp: 83, att: 55, def: 90, spa: 130, spd: 81, spe: 86),
    ability: Ability.toxicDebris,
    ability2: null,
    hiddenAbility: Ability.corrosion,
    moves: glimmoraMoves,
    mega: Pokemon(
      id: 970,
      type1: Type.rock,
      type2: Type.poison,
      stats: Stats(hp: 83, att: 90, def: 105, spa: 150, spd: 96, spe: 101),
      ability: Ability.adaptability,
      moves: glimmoraMoves,
      form: 'Mega',
    ),
  ),

  'farigiraf': Pokemon(
    id: 981,
    type1: Type.normal,
    type2: Type.psychic,
    stats: Stats(hp: 120, att: 90, def: 70, spa: 110, spd: 70, spe: 60),
    ability: Ability.cudChew,
    ability2: Ability.armorTail,
    hiddenAbility: Ability.sapSipper,
    moves: farigirafMoves,
  ),

  'kingambit': Pokemon(
    id: 983,
    type1: Type.dark,
    type2: Type.steel,
    stats: Stats(hp: 100, att: 135, def: 120, spa: 60, spd: 85, spe: 50),
    ability: Ability.defiant,
    ability2: Ability.supremeOverlord,
    hiddenAbility: Ability.pressure,
    moves: kingambitMoves,
  ),
  'sinistcha': Pokemon(
    id: 1013,
    type1: Type.grass,
    type2: Type.ghost,
    stats: Stats(hp: 71, att: 60, def: 106, spa: 121, spd: 80, spe: 70),
    ability: Ability.hospitality,
    ability2: null,
    hiddenAbility: Ability.heatproof,
    moves: sinistchaMoves,
  ),

  'archaludon': Pokemon(
    id: 1018,
    type1: Type.steel,
    type2: Type.dragon,
    stats: Stats(hp: 90, att: 105, def: 130, spa: 125, spd: 65, spe: 85),
    ability: Ability.stamina,
    ability2: Ability.sturdy,
    hiddenAbility: Ability.stalwart,
    moves: archaludonMoves,
  ),

  'hydrapple': Pokemon(
    id: 1019,
    type1: Type.grass,
    type2: Type.dragon,
    stats: Stats(hp: 106, att: 80, def: 110, spa: 120, spd: 80, spe: 44),
    ability: Ability.supersweetSyrup,
    ability2: null,
    hiddenAbility: Ability.regenerator,
    moves: hydrappleMoves,
  ),
};
